language: node_js

sudo: required

services:
  - docker

node_js:
  - node # will use latest node

before_script: # commands to run before the build step
  - yarn install

script: # the build step
  - ng build --prod

cache:
  directories:
    - "$HOME/google-cloud-sdk/"
after_success:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; curl https://sdk.cloud.google.com | bash; fi
  # Add gcloud to $PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
  - gcloud --quiet components update kubectl
  # Auth flow
  - echo $GCLOUD_KEY | base64 --decode > /home/travis/gcloud.json
  - gcloud auth activate-service-account $GCLOUD_EMAIL --key-file /home/travis/gcloud.json
  - ssh-keygen -f ~/.ssh/google_compute_engine -N ""
  # Push to Google container registry
  - docker build -t eu.gcr.io/bb-hackathon/frontend:$TRAVIS_COMMIT .
  - gcloud container clusters get-credentials hackathon
  - gcloud docker -- push eu.gcr.io/bb-hackathon/frontend:$TRAVIS_COMMIT
  - if [ "develop" == $TRAVIS_BRANCH ]; then kubectl set image deployment/frontend frontend=eu.gcr.io/bb-hackathon/frontend:$TRAVIS_COMMIT; fi
